config/routes.rb
Rails.application.routes.draw do
  root 'places#index'
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :name
  belongs_to :experience
  after_create :send_comment_email

  RATINGS = {
    'one star': '1_star',
    'two stars': '2_stars',
    'three stars': '3_stars',
    'four stars': '4_stars',
    'five stars': '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end 

  def send_comment_email
      NotificationMailer.comment_added(self).deliver_now
  end 
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/comments/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Comment Details</h1>
 <%= simple_form_for @comment do |f| %>
    <%= f.input :name %>
    <%= f.input :experience %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Static</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
     <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Static</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'New Comment', new_comment_path, class: 'nav-link' %>
          </li>
      </div>
    </nav>
    <%= yield %>
   </div>

    <div class="footer">
      <div class="container">
        <div class="row">
          <p class="text-muted">Built by Darrell Girty.</p>
        </div>
      </div>
    </div> 
  </body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<h1> Welcome to my Static Web Page</h1>


<h2> This has been a very challenging eight weeks to say the least. I started this coarse with absolutely no web developement background at all. I have tried to get a positive outlook during the whole process. Somedays have proved more challenging than others!! I look forward to continue growth and knowledge while in this course.</h2>



<p>This is a static home page in a Rails application.</p>

app/views/places/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Comments</h1>
  <%= simple_form_for @comment do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>